# Generated by Django 4.2.27 on 2026-06-14 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseagreement',
            name='agreement_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
