# Generated by Django 4.2.27 on 2026-06-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0003_installment_standpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('general', 'General'), ('development', 'Development'), ('stand', 'Stand')], default='general', max_length=15)),
                ('development_slug', models.CharField(blank=True, max_length=120)),
                ('development_name', models.CharField(blank=True, max_length=255)),
                ('stand_number', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(default='website', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('closed', 'Closed')], db_index=True, default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='developments.purchaseagreement')),
                ('development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='developments.developmentproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='development_status_928e86_idx'), models.Index(fields=['kind'], name='development_kind_a5f134_idx')],
            },
        ),
    ]
