# Generated by Django 4.2.27 on 2026-06-14 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_chartofaccount_balance_sheet_category'),
        ('developments', '0004_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseagreement',
            name='sale_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journal'),
        ),
    ]
