# Generated by Django 4.2.27 on 2026-06-17 15:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developments', '0005_purchaseagreement_sale_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=120)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('selling', 'Selling'), ('sold_out', 'Sold out'), ('completed', 'Completed')], default='planning', max_length=12)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('target_completion', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='developments.developmentproject')),
            ],
            options={
                'ordering': ['project', 'sequence'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('position', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('offered', 'Offered'), ('converted', 'Converted'), ('removed', 'Removed')], db_index=True, default='waiting', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='developments.phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='developments.developmentproject')),
                ('stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='developments.stand')),
            ],
            options={
                'ordering': ['phase', 'position', 'id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TitleTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('stage', models.CharField(choices=[('not_started', 'Not started'), ('docs_prep', 'Documents in preparation'), ('lodged', 'Lodged at Deeds Office'), ('assessed', 'Assessed'), ('duty_paid', 'Transfer duty paid'), ('registered', 'Registered'), ('title_issued', 'Title deed issued')], db_index=True, default='not_started', max_length=14)),
                ('deeds_reference', models.CharField(blank=True, max_length=80)),
                ('conveyancer', models.CharField(blank=True, max_length=160)),
                ('lodged_date', models.DateField(blank=True, null=True)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title_transfer', to='developments.purchaseagreement')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='developments.stand')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PriceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Launch, Foundation complete, Roof on', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_steps', to='developments.phase')),
            ],
            options={
                'ordering': ['phase', 'effective_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=200)),
                ('trade', models.CharField(blank=True, max_length=120)),
                ('contract_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('retention_percent', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('paid_to_date', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='developments.developmentproject')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('phase', models.CharField(blank=True, help_text='Block / phase, optional', max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('percent_complete', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('complete', 'Complete')], db_index=True, default='not_started', max_length=12)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cardinal_construction/')),
                ('notes', models.TextField(blank=True)),
                ('payment_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('payment_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='developments.developmentproject')),
            ],
            options={
                'ordering': ['project', 'sequence'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('category', models.CharField(choices=[('land', 'Land'), ('civils', 'Civils / servicing'), ('construction', 'Construction'), ('professional', 'Professional fees'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('other', 'Other')], default='construction', max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='developments.developmentproject')),
            ],
            options={
                'ordering': ['project', 'category', 'id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='stand',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stands', to='developments.phase'),
        ),
        migrations.CreateModel(
            name='SnagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='e.g. Kitchen, Boundary wall', max_length=120)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('fixed', 'Fixed'), ('verified', 'Verified')], db_index=True, default='open', max_length=10)),
                ('assigned_to', models.CharField(blank=True, help_text='Contractor', max_length=160)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cardinal_snags/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snags', to='developments.purchaseagreement')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snags', to='developments.stand')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='development_status_07a9b9_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('reservation_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=50)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('hold_days', models.PositiveIntegerField(default=7)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=12)),
                ('source', models.CharField(default='website', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='developments.purchaseagreement')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='developments.buyer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='developments.stand')),
            ],
            options={
                'ordering': ['-reserved_at', '-id'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='development_status_4034b7_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='phase',
            index=models.Index(fields=['project', 'sequence'], name='development_project_a00876_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionmilestone',
            index=models.Index(fields=['project', 'sequence'], name='development_project_c59675_idx'),
        ),
    ]
